app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('',views.IndexMain.as_view()),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # 글 목록
    path("", views.PostList.as_view(), name='list'),
    # 글 작성
    path("write/", views.PostCreate.as_view(), name='write'),
    # 글 상세
    path("detail/<int:pk>/", views.PostDetail.as_view(), name='detail'),
    # 글 수정
    path("detail/<int:pk>/edit/", views.PostUpdate.as_view(), name='edit'),
    # 글 삭제
    path("detail/<int:pk>/delete/", views.PostDelete.as_view(), name='delete'),
    # 글 검색
    path("search/<str:tag>/", views.PostSearch.as_view(), name="search"),

    # 댓글 작성
    path("detail/<int:pk>/", views.CommentCreate.as_view(), name="cm-write"),
    # 댓글 수정
    path("detail/<int:pk>/", views.CommentUpdate.as_view(), name="cm-edit"),
    # 댓글 삭제
    path("detail/<int:pk>/", views.CommentDelete.as_view(), name="cm-delete"),

    # # 대댓글 작성
    # path("detail/<int:pk>/", views.ReCommentCreate.as_view(), name="re_write"),
    # # 대댓글 수정
    # path("detail/<int:pk>/", views.ReCommentUpdate.as_view(), name="re_edit"),
    # # 대댓글 삭제
    # path("detail/<int:pk>/", views.ReCommentDelete.as_view(), name="re_delete"),

]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'user'

urlpatterns = [
    # 회원가입
    path('register/', views.Signup.as_view(),name='register'),
    # 로그인
    path('login/', views.UserLogin.as_view(),name='login'),
    # 로그아웃
    path('logout/', views.UserLogout.as_view(),name='logout'),
    # 회원정보
    path('profile/', views.profile, name='profile'),
    # 회원탈퇴
    path('withdrawal/', views.UserDrawal.as_view(),name='withdrawal'),
]

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.

class Post(models.Model):
    CATEGORY = (
        ('C-Lang' , 'C-Lang'),
        ('C++', 'C++'),
        ('Java', 'Java'),
        ('Python', 'Python'),
        ('HTML5', 'HTML5'),
        ('CSS', 'CSS'),
        ('Django', 'Django')

    )
    title = models.CharField(null=False, blank=False, max_length=50)
    content = models.TextField()
    category = models.CharField(max_length=20, null=True, blank=True, choices=CATEGORY)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    visible = models.BooleanField(default=True)
    
    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    inheritance = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    visible = models.BooleanField(default=True)

    def __str__(self):
        return self.content[:10]

blog/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = [ 'title', 'content', 'category']

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = [ 'content' ]
        widget = {
            'content' : forms.Textarea(attrs = { 'row' : '3', 'cols' : '25'})
        }

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.urls import reverse_lazy, reverse

# Create your views here.

### Index
# class Index(View):
#     def get(self, request):
#         pass
#     def post(self, request):
#         pass


### Post
class PostList(View):
    def get(self, request):
        posts = Post.objects.all().order_by('-created_at')
        context = {
            'posts' : posts,
            'title' : "BlogPostsPage"
        }

        return render(request, 'blog/post_list.html', context)


class PostCreate(LoginRequiredMixin, View):
    def get(self, request):
        form = PostForm()
        context = {
            'form' : form,
            'title' : "Blog"
        }

        return render(request, 'blog/post_form.html', context)
    
    def post(self, request):
        form = PostForm(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.writer = request.user
            post.save()
            return redirect('blog:list')
        
        context = {
            'form' : form
        }

        return render(request, 'blog/post_form.html', context)


class PostDetail(View):

    def get(self, request, pk):
        post = Post.objects.prefetch_related('comment_set').get(pk=pk)

        comments = post.comment_set.all()

        comment_form = CommentForm

        context = {
            "title" : "BlogPost",
            'post_id' : pk,
            'post_title' : post.title,
            'post_writer' : post.writer,
            'post_content' : post.content,
            'post_updated_at' : post.updated_at,
            'comments' : comments,
            'comment_form' : comment_form,
        }

        return render(request, 'blog/post_detail.html', context)


class PostUpdate(View):

    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        form = PostForm(initial={'title':post.title, 'content': post.content, 'category':post.category})
        context = {
            'form' : form,
            'post' : post,
            "title" : "BlogEdit",
        }

        return render(request, 'blog/post_edit.html', context)

    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        form = PostForm(request.POST)

        if form.is_valid():
            post.title = form.cleaned_data['title']
            post.content = form.cleaned_data['content']
            post.save()
            return redirect('blog:detail', pk=pk)
        
        context = {
            'form' : form,
            "title" : "BlogPost"
        }

        return render(request, 'blog/post_edit.html', context)


class PostDelete(View):

    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        post.visible = False
        post.save()
        return redirect('blog:list')


class PostSearch(View):
    def get(self, request):
        pass
    def post(self, request):
        pass


### Comment
class CommentCreate(LoginRequiredMixin, View):
    
    def post(self, request, pk):
        form = CommentForm(request.POST)
        post = get_object_or_404(Post, pk=pk)

        if form.is_valid():
            content = form.cleaned_data['content']
            writer = request.user

            try:
                comment = Comment.objects.create(post=post, content=content, writer=writer)
            except ObjectDoesNotExist as e:
                print('Post does not exist.', str(e))
            except ValidationError as e:
                print('Valdation error occurred', str(e))
            
            return redirect('blog:detail', pk=pk)
        
        context = {
            "title": "Blog",
            'post_id': pk,
            'comments': post.comment_set.all(),
            'comment_form': form
        }
        return render(request, 'blog/post_detail.html', context)



class CommentUpdate(View):
    def get(self, request):
        pass
    def post(self, request):
        pass



class CommentDelete(View):
    def post(self, request, pk):
        Comment = get_object_or_404(Comment, pk=pk)
        Comment.visible = False
        Comment.save()
        return redirect('blog:list')



# ### ReComment
# class ReCommentCreate(View):
#     def get(self, request):
#         pass
#     def post(self, request):
#         pass



# class ReCommentUpdate(View):
#     def get(self, request):
#         pass
#     def post(self, request):
#         pass



# class ReCommentDelete(View):
#     def get(self, request):
#         pass
#     def post(self, request):
#         pass

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
  <h2>{% trans "Title :" %} {{ post_title }}</h2>
    
  {% if post_writer == request.user %}
    <a href="{% url 'blog:edit' pk=post_id %}" class="btn">{% trans "수정" %}</a>
    <form action="{% url 'blog:delete' pk=post_id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="{% trans 'Delete' %}" class="btn">
    </form>
  {% endif %}

    <p>{% trans 'Content:' %} {{ post_content }}</p>
    <p>{% trans 'Writer:' %} {{ post_writer }}</p>
    <p>{% trans 'Date:' %} {{ post_updated_at }}</p>

    <br><br>
    <!-- 작성 화면 -->
    <h3>댓글</h3>
    <form action="{% url 'blog:cm-write' pk=post_id %}" method="post">
        {% csrf_token %}
        {% if comment_form.errors %}
            {% with form=comment_form %}
                {% include 'blog/form_error.html' %}
            {% endwith %}
        {% else %}
            {{ comment_form.content }}
        {% endif %}
        <input type="submit" value="{% trans 'submit' %}">
    </form>
    <br>
    
    <!-- comments -->
    {% if comments %}
        <ul>
            {% for comment in comments %}
                <li>{{ comment.content }} / {{ comment.created_at }} / {{ comment.writer }}
                    {% if comment.writer == request.user %}
                        <form action="{% url 'blog:cm-delete' pk=comment.pk %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="X" class='btn'>
                        </form>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>{% trans 'There is no comment.' %}</p>
    {% endif %}
    <hr>


{% endblock content %}

blog/templates/blog/post_edit.html
{% extends "base.html" %}

{% block content %}
<h3>수정을 해봅시다</h3>
<form action="{% url 'blog:edit' pk=post.pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="수정">
</form>
{% endblock content %}

blog/templates/blog/post_form.html
{% extends "base.html" %}
{% block JSscript %}
  
{% endblock JSscript %}
{% block content %}
<form action="{% url 'blog:write' %}" method="post" id="textbox">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-outline-success">
</form>
{% endblock content %}

blog/templates/blog/post_list.html
{% extends "base.html" %}

{% block content %}
  <p class="main-title">블로그 게시판의 첫 화면</p>
  {% if user.nickname == null %}
  <p>당신은 게스트로 접속했습니다. 작성 및 수정이 불가능합니다.</p>
  {% else %}
  <p>안녕하세요 {{ user.nickname }}님</p>
  <form action="{% url 'user:profile' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="프로필보기">
  </form>
  {% endif %}
  
  {% if posts %}
    <table class="table">
        <thead class="table-light">
            <tr>
                <td>제목</td>
                <td>작성자</td>
                <td>작성일자</td>
            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
              <tr>
                {% if post.visible == True %}
                  
                <td><a href="{% url 'blog:detail' pk=post.pk %}" class="btn">{{ post.title }}</a></td>
                <td>{{ post.writer }}</td>
                <td>{{ post.updated_at }}</td>
                {% endif %}
              </tr>
            {% endfor %}
        </tbody>
    </table>
  {% else %}
    <h1>현재 작성된 글이 없습니다.</h1>
  {% endif %}
  <form action="{% url 'blog:write' %}" method="get">
    <input type="hidden" name="'{{ redirect_field_name }}" value="{{ request.GET.next }}">
    <input type="submit" value="글 작성">
  </form>
  <form action="{% url 'user:logout' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="로그아웃">
  </form>
{% endblock content %}

blog/templates/blog/post_search.html
{% extends "base.html" %}
{% block content %}
  <p>이건 글의 검색 결과입니다.</p>
{% endblock content %}