app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('',views.IndexMain.as_view()),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # 글 목록
    path("", views.PostList.as_view(), name='list'),
    # 글 작성
    path("write/", views.PostCreate.as_view(), name='write'),
    # 글 상세
    path("detail/<int:pk>/", views.PostDetail.as_view(), name='detail'),
    # 글 수정
    path("detail/<int:pk>/edit/", views.PostUpdate.as_view(), name='edit'),
    # 글 삭제
    path("detail/<int:pk>/delete/", views.PostDelete.as_view(), name='delete'),
    # 글 검색
    path("search/<str:tag>/", views.PostSearch.as_view(), name="search"),

    # 댓글 작성
    path("detail/<int:pk>/", views.CommentCreate.as_view(), name="cm-write"),
    # 댓글 수정
    path("detail/<int:pk>/", views.CommentUpdate.as_view(), name="cm-edit"),
    # 댓글 삭제
    path("detail/<int:pk>/", views.CommentDelete.as_view(), name="cm-delete"),

    # # 대댓글 작성
    # path("detail/<int:pk>/", views.ReCommentCreate.as_view(), name="re_write"),
    # # 대댓글 수정
    # path("detail/<int:pk>/", views.ReCommentUpdate.as_view(), name="re_edit"),
    # # 대댓글 삭제
    # path("detail/<int:pk>/", views.ReCommentDelete.as_view(), name="re_delete"),

]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'user'

urlpatterns = [
    # 회원가입
    path('register/', views.Signup.as_view(),name='register'),
    # 로그인
    path('login/', views.UserLogin.as_view(),name='login'),
    # 로그아웃
    path('logout/', views.UserLogout.as_view(),name='logout'),
    # 회원정보
    path('profile/', views.profile, name='profile'),
    # 회원탈퇴
    path('withdrawal/', views.UserDrawal.as_view(),name='withdrawal'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>
        {% block title %}
          {{ title }}
        {% endblock title %}
    </title>
</head>
<body>
    <div class="contatiner">
        {% block content %}
        <p>Welcome, StartPage</p>
          
        {% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1>Here is IndexPage</h1>
  <h2>{% trans "Hello World" %}</h2>
  <a href="{% url 'blog:list' %}">게시판으로</a>
  <a href="{% url 'user:login' %}">로그인</a>
{% endblock content %}